### ISSUE TITLE
Telescopic weapon problem

### ISSUE THREAD

**Issue by aionchs** [Jonathan57500/aion-lightning-2.7#1]
- [Hello administrator, I found a BUG about two-handed weapons.
If the main hand using retractable weapons, deputy non-retractable weapons can attack 5M, but Ncsoft version is not the case. It must be two weapons are telescopic weapons can be achieved, may I fix this BUG?

**Comment by Jonathan57500** [comment]
Hi @aionchs thank you for participating to this project 👍 
The biggest difficulty is to know if this is a bug in 2.7 from Gameforge or if it's a new feature that has been added or modified by NC-Soft in next versions.
The correct way to do is find somewhere over the net the proof this is a bug and not an update/change from next versions, then yes you can fix it and make a pull request.
If this is an update of NC-Soft in next versions, you can make a fix but add a configuration option in .properties files to allow other administrators enable this feature or not.

**Comment by Jonathan57500** [comment]
Please open a new issue if you can't fix it.
