### ISSUE TITLE
The client brakes when it is connected through a local network

### ISSUE THREAD

**Issue by padlyuck** [Jonathan57500/aion-lightning-2.7#10]
Hi! I'm trying to setup server in my local network. Everything goes well when the server and the client are running on the same machine. But when I trying to play from another machine I see something like this 
![image](https://pp.userapi.com/c849028/v849028935/29c43/2GJsfknKSJc.jpg)
Before making this screen I choose server, start creating a new char, choose race and class.  Please tell me what I'm doing wrong?
Here is my LS network.properties config:
```
loginserver.network.client.port = 2106
loginserver.network.client.host = *
loginserver.network.client.logintrybeforeban = 5
loginserver.network.client.bantimeforbruteforcing = 15
loginserver.network.gameserver.host = *
loginserver.network.gameserver.port = 9014
loginserver.network.nio.threads.read = 1
loginserver.network.nio.threads.write = 1
loginserver.accounts.autocreate = true
loginserver.server.maintenance = false
loginserver.server.maintenance.gmlevel = 3
loginserver.server.age.limit.enable = false
loginserver.server.age.limit.level = 16
loginserver.server.floodprotector = true
loginserver.server.bruteforceprotector = true
loginserver.server.pingpong = true
loginserver.server.pingpong.delay = 3000
network.fastreconnection.time = 1
loginserver.excluded.ips = 
```
GS network.properties:
```
gameserver.network.client.port = 7777
gameserver.network.client.host = *
gameserver.network.client.maxplayers = 100
gameserver.network.login.address = localhost:9014 
gameserver.network.login.gsid = 1
gameserver.network.login.password = aion
gameserver.network.chat.address = localhost:9021
gameserver.network.chat.password = aion
gameserver.network.nio.threads = 1
gameserver.network.packet.processor.threads.min = 4
gameserver.network.packet.processor.threads.max = 4
gameserver.network.packet.processor.threshold.kill = 3
gameserver.network.packet.processor.threshold.spawn = 50
gameserver.network.display.unknownpackets = false
gameserver.network.flood.connections = false
gameserver.network.flood.tick = 1000
gameserver.network.flood.short.warn = 10
gameserver.network.flood.short.reject = 20
gameserver.network.flood.short.tick = 10
gameserver.network.flood.long.warn = 30
gameserver.network.flood.long.reject = 60
gameserver.network.flood.long.tick = 60
```
GS ipconfig.xml:
```xml
<ipconfig default="192.168.1.100"><!--server IP-->
    <!-- My subnet -->
    <iprange min="192.168.1.0" max="192.168.1.255" address="192.168.1.100"/>
</ipconfig>
```
The result is the same regardless of the server operating system. Ports on server machine are opened for TCP connections other programms works fine through the network.
Please help me deal with this problem.

**Comment by Jonathan57500** [comment]
Looks like a database error, what does error message means?
You should try to pick a 2.7 original client.
Give me console logs when you try to create new character

**Comment by padlyuck** [comment]
No there are no error messages. Client shows new interface windows but not hides previos.
![image](https://pp.userapi.com/c834400/v834400385/190d25/ahuhbnd0_gI.jpg)

**Comment by padlyuck** [comment]
console.log of login and game servers contains only [INFO] messages, no warnings or errors

**Comment by Jonathan57500** [comment]
Try to remove your ip subnet `<iprange min="192.168.1.0" max="192.168.1.255" address="192.168.1.100"/>` then you should connect from any computer in your network
If you don't have any error message from client and from server, I'm afraid I can support you, this is probably due to an incompatible client.

**Comment by padlyuck** [comment]
Ok, i'll try to remove this tag. Can you share those version of client on which you testing your builds? i'll try to test with this version too

**Comment by Jonathan57500** [comment]
Normally it should work with all clients 2.7.X.X but I'm using 2.7.0.2 EU client from Gameforge

**Comment by padlyuck** [comment]
my version is the same, but i download it from torrent, so i'm not sure that it is original version. please share your client or give me a direct link where i can download yours version of client

**Comment by padlyuck** [comment]
Hi @Jonathan57500 I tried to remove subnet from network.xml, but it doesn't make effect. Have you any other ideas?

**Comment by padlyuck** [comment]
You was right. it was problem on client side

**Comment by padlyuck** [comment]
@shev92k70  I have only russian client, but the server from which it was downloaded is now disabled

**Comment by shev92k70** [comment]
@padlyuck , Awesome! I need russian client and I want to create my server, so, it's ok for me. 
Could you please give me this client? :)
Буду очень благодарен :D

**Comment by padlyuck** [comment]
@shev92k70 поищу на внешних жестких, отпишусь

**Comment by shev92k70** [comment]
@padlyuck , спасибо, буду ждать

**Comment by padlyuck** [comment]
@shev92k70 не нашел. походу он лежал на недавно почившем жестком)) Поищи на торрентах или пиратских серверах. я свою копию качал с simplyaion, но он походу скопытился

**Comment by Jonathan57500** [comment]
Please do not comment in other language than English.
I can't assist on the client, it will take a very long time for me to put my 2.7 client over the net.

**Comment by shev92k70** [comment]
@Jonathan57500 , got it, sorry. 
@padlyuck , so, do you have any updates for me regarding the client 2.7?
@Jonathan57500 , @padlyuck , maybe you can just create a .torrent file from the client? 
And I'll just download it. 
And actually I found one english version of 2.7 client and it's work for me with yours server. 
But I need the russian version :(

**Comment by padlyuck** [comment]
@shev92k70 sorry, it was on crashed hdd. try to search for a free russian servers like simplyaion.ru(now unavailable)

**Comment by shev92k70** [comment]
@padlyuck , understood. No problem. Thanks for your trying 👍
