### ISSUE TITLE
Cmdrevenge

### ISSUE THREAD

**Issue by teddyekachi** [Jonathan57500/aion-lightning-2.7#11]
Erreur lors de la compilation a cause de la commande cmd revenge , il faut enlever les caractères russes ^^

**Comment by Jonathan57500** [comment]
Hm tu risques de rencontrer le même problème à plusieurs autres moments, au tout début du travail sur cet émulateur certains commentaires dans le code ont été écrits en français avec les accents, du coup parfois il génère une erreur lors de la compilation ou de l'accès à une de ces méthodes commentée en français.
La bonne solution en attendant que le code soit propre, c'est de rajouter une variable d'environnement:
`JAVA_TOOL_OPTIONS = -Dfile.encoding=ISO-8859-1`

**Comment by teddyekachi** [comment]
Je n'ai eu aucun d'autre problème personnellement , juste ce CMD, mais merci quand même ça sera utile :)

**Comment by Jonathan57500** [comment]
Fixed
