### ISSUE TITLE
About the client

### ISSUE THREAD

**Issue by aionchs** [Jonathan57500/aion-lightning-2.7#13]
Hello developer, do you have a BIN file for the 64-bit client?

**Comment by Jonathan57500** [comment]
Hi, no there is not as its compatibility was nos guaranted by NCSoft in 2011/2012. On retails servers, NCSoft said to not use 64 bits launcher because it caused crashs and others.
There is no real reason to launch Aion 2.7 in 64 bits as the game didn't require so much ram or global performance.
