### ISSUE TITLE
Weddings not work!

### ISSUE THREAD

**Issue by Dylen67** [Jonathan57500/aion-lightning-2.7#17]
Hi

Weddings not work!
Wedding is allowed
Command: // marry [Player 1] [Player 2] not work.
I'm sorry to bother you!
My  weddings.properties : 
# ----------------------------
# Weddings config's:
# ----------------------------

# Enable weddings
# Default: false
gameserver.weddings.enable = true

# Enable giving gifts after weddings
# Default: false
gameserver.weddings.gift.enable = false

# Gift item id
gameserver.weddings.gift = 0

# Enable required suit
# Default: false
gameserver.weddings.suit.enable = false

# Suit id's (required only one of list)
# Example: 111111111, 222222222
gameserver.weddings.suit = 

# Required membership for wedding
# Default: 0
gameserver.weddings.membership = 0

# Required membership for use weddings commands
# Default: 0
gameserver.weddings.command.membership = 0

# Enable same-sex weddings
# Default: false
gameserver.weddings.same_sex = false

# Enable weddings between races
# Default: false
gameserver.weddings.races = false

# Required kinah count
# Default: 0
gameserver.weddings.kinah = 0

# Announce weddings in world chat
# Default: true
gameserver.weddings.announce = true

Thanks

**Comment by Jonathan57500** [comment]
Please test, Admin command has been fixed
