### ISSUE TITLE
Weddings

### ISSUE THREAD

**Issue by Dylen67** [Jonathan57500/aion-lightning-2.7#18]
Hi

Marriage command works but did not go to the database.
Command: //missyou do not work always says the player is not online.
Command: //cometome do not work always says the player is not online.

**Comment by Dylen67** [comment]
Is there no idea for a solution?

**Comment by Jonathan57500** [comment]
Hi, sorry I was missing 3 last weeks.
This fix should be easy to do, just change the number of parameters that the command is waiting (one less generally) as they are commands from another version of emulator.
Please fork this depot, fix and test, and then create a new pull request :)

**Comment by Dylen67** [comment]
Hi!

Client Version=2.7.0.2

Emu version=?

**Comment by Jonathan57500** [comment]
Don't understand this question as an emulator didn't have a proper version. An emulator is compatible with a client regarding the packets that the client send and make a correct treatment of them and correct response of them.
This emulator is compatible with a 2.7.0.X client (and successfully tested with a 2.7.0.2 client EN/FR from Gameforge)

**Comment by Dylen67** [comment]
Hi!

Please help me in correcting the mistake. Unfortunately I could not solve this marriage mistake yet.

Thanks

**Comment by Jonathan57500** [comment]
Hi,
I've made all tests, everything is working correctly on my side.
Insertion in Database is OK
Both user commands .cometome and .missyou are OK each time

Please make a fresh install of this server and then post instructions to reproduce this issue.
