### ISSUE TITLE
BALAUR not attack!

### ISSUE THREAD

**Issue by Dylen67** [Jonathan57500/aion-lightning-2.7#20]
Hi!

BALAUR does not attack Inggison, Gelkmaros Fortress.

Is your idea possible?

Thanks

**Comment by Jonathan57500** [comment]
Hi,
Balaurs didn't attack any fortress (Balaurea nor Reshanta) as this functionnality is not correctly coded.
To create an emulator, first step is to sniffing packets exchange between client and retail server, but Balaur assaults seems to be full server side functionnality, I think this is why it is not correclty coded in most emulator.
This is not a bug as it did not really exists (you can find some code sample somewhere about balaur assault but it's not working), we need somebody able to create this content.

**Comment by Jonathan57500** [comment]
Added to TODO list
