### ISSUE TITLE
How do I add authentication IP？

### ISSUE THREAD

**Issue by lrz2010** [Jonathan57500/aion-lightning-2.7#21]
How do I add authentication IP？
I can't use fixed public network IP，Tips not on the authentication server。

**Comment by Jonathan57500** [comment]
Can you please explain with more details what is you request?
I don't understand "authentication IP" (what is that?) and "fixed public network IP" (what is that?)

**Comment by lrz2010** [comment]
Thank you for your reply，I have grappled with this question，But I have another problem.
Why does NPC(guard) not actively attack monsters?
![qq 20181212003500](https://user-images.githubusercontent.com/44985031/49815025-ca48cd00-fda5-11e8-8f6e-c31e97f20386.jpg)

**Comment by Jonathan57500** [comment]
This depends on tribe relations between npc; not all npc should attack all boss or monsters.
You must compare AL-Game\data\static_data\tribe\tribe_relations.xml to tribes in AL-Game\data\static_data\npcs\npc_templates.xml

**Comment by lrz2010** [comment]
Thank you very much!

**Comment by lrz2010** [comment]
Hi! I had a problem.
Can you help me ?
Why does the client receive messy information?
I use Chinese.
I try to add utf-8 at compile time，but it still doesn't work.
![qq 20181213064927](https://user-images.githubusercontent.com/44985031/49903791-4543dd80-fea3-11e8-9468-643844620e02.png)

**Comment by Jonathan57500** [comment]
Please open separate topics for different problems
You must use Unicode for special char
