### ISSUE TITLE
Why does each character have a [1] after its name?

### ISSUE THREAD

**Issue by lrz2010** [Jonathan57500/aion-lightning-2.7#22]
Hello developer,Why does each character have a [1] after its name?
If I set my account to GM, that would not happen.
![g1ugt kxme3 aw1xybb1 p](https://user-images.githubusercontent.com/44985031/50070952-05665880-020b-11e9-96b8-97e6f2a1b12f.png)
![qq 20181217144733](https://user-images.githubusercontent.com/44985031/50070953-05665880-020b-11e9-95fb-2059b0f50d11.png)
![qq 20181217144337](https://user-images.githubusercontent.com/44985031/50070954-05feef00-020b-11e9-8a71-40c7668eb07e.jpg)

**Comment by Jonathan57500** [comment]
This is a beta functionnality (custom PvE rank, a way to add a players ranking based on PvE).
It is not finished yed, please be sure that this is disabled on your server (AL-Game/config/custom/customfun.properties ==> gameserver.custom.customfun.customrank.enable = false)

**Comment by lrz2010** [comment]
Thank you very much!

**Comment by Jonathan57500** [comment]
I don't understand the question.
We provide assistance only on emulator itself, not on client or installation.

**Comment by lrz2010** [comment]
Ok,thank you for your help!
