### ISSUE TITLE
Announcements not work

### ISSUE THREAD

**Issue by lrz2010** [Jonathan57500/aion-lightning-2.7#23]
Hello developer,happy new year！
//announcement all ALL SYSTEM 2700 happy new year! -Help information appears
//announcement list -Help information appears too！
![qq 20181231174848](https://user-images.githubusercontent.com/44985031/50557895-63735f80-0d24-11e9-9564-7f66c29c4c86.png)

Other，If I open any event，When siege start, there will be two bosses，and double the monster.
![qq 20181231175323](https://user-images.githubusercontent.com/44985031/50558000-412e1180-0d25-11e9-877a-e2a8bcb987cd.png)

**Comment by Jonathan57500** [comment]
Fixed `//announcement list`
Please be carreful: `//announcement all ALL SYSTEM 2700 happy new year!` is not correct, must be `//announcement add ALL SYSTEM 2700 happy new year!`

**Comment by lrz2010** [comment]
Thank you for your reply.
I useing //announcement add，That's my input error.
Other,why when seige start,There will be two boss。

**Comment by Jonathan57500** [comment]
Please open separate topic for different issues for better following.
This problem is not existing with normal running of a server. We fixed a similar issue a few years ago when GM used //spawn command (in some conditions, use of //spawn command with spawn all forteress npc twice)
