### ISSUE TITLE
Client and Bin32

### ISSUE THREAD

**Issue by Jonathan57500** [Jonathan57500/aion-lightning-2.7#26]
Hi,
Can some of you post a link to download an Aion 2.7.0.1 client and a valid Bin32 folder (included or not) and specify the included languages ?
I'll then put these links into project Wiki.
Thank you :)

**Comment by Jonathan57500** [comment]
I don't need anything, the idea is to make a list of different available client that are working with this emulator. In this way if anybody wants to create a 2.7 server in any region (NA, EU, Asia) they can clone this emu and get access to a client list that they can share with their players

**Comment by davirodr8** [comment]
I'll test this emulator. chinese client is same, just change language

**Comment by davirodr8** [comment]
can you post the compiled emulator?

**Comment by lrz2010** [comment]
So, do I need to post the download address of the Chinese client?

**Comment by davirodr8** [comment]
if u can. I have this link ( 2.7客户端：
http://pan.baidu.com/share/link?shareid=4184545692&uk=4160987512 ) , but i can't find the password to extract.

**Comment by lrz2010** [comment]
This is the client I use. IF you need this client，Can you provide me with a website of your commonly used network hard disk?

**Comment by YazooXepher** [comment]
Can you put your client on another platform of download that Chinese please?

**Comment by lrz2010** [comment]
Yes I can,but I don't have another platform website

**Comment by dezalmado** [comment]
https://mega.co.nz/#%21DUlgBKYB%21gr_ZmSDsdHARXHHm_U9QDk7znNj33dOuAOrTn4CdVTc

Aion EU 2.7.0.2

http://www.mediafire.com/file/wtxf7nnnc9sfcqt/Downgrade2701v4.rar

aion Downgrade 2.7.0.1
http://forum.ragezone.com/f590/aion-2-7-client-1121613/
