### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by christophheich** [Jonathan57500/aion-lightning-2.7#28]
Hey, i am interested in the Project, even though i am having a similar Aion Lightning Version i worked on since 2015. 

It's used for a server called Empyrean Calling, i am currently restructuring it, had some years ago issues with the JDK like u45 fckd up remove shock while u43 hadn't this problem - i am curious if this version of AL has similar issues.

Honestly github and open source is a cool thing, but ncsoft took so many sources down (aprx. 10 i forked from Google when they shutdown their server) - they are gone now, at least the specific versions with their commits.

DMCA Takedown: https://github.com/github/dmca/blob/master/2016/2016-04-07-NCSOFT.md

Maybe we could work together on this project.

Oh yea and for sure i do have a client, as i am running a server (i will reupload everything and send you the gdrive link)

**Comment by Jonathan57500** [comment]
Hi,

I'm happy to see your message, would be nice if we could work together on this project :)
I know Empyrean Calling, I played on your server (for tests :p) and I'm using your Carbonizer for Windows 10 Cam fix.

Aion is a dying game, even for old school versions, players don't want true difficulty this game was before 4.0 (or 3.5 for haters ^^) anymore.

When Github will destroy this depot, I'll reopen it somewhere else like every time, but now that Github is property of Microsoft, I hope they will take as long time as Internet Explorer speed to close it :D

I'm open for a larger discussion if you wish =)

**Comment by Jonathan57500** [comment]
No news from the developer since end of march, closing discussion
