### ISSUE TITLE
SKILLS

### ISSUE THREAD

**Issue by determinated** [Jonathan57500/aion-lightning-2.7#29]
Missing alot of skill motions, many bugs on skills.

**Comment by determinated** [comment]
Check the skill motion of the other versions. This version got many bugs on it.
It's a source bug.

**Comment by Jonathan57500** [comment]
Hi,
Yes skills have to be reworked for most of them. You can probably help on fixing a few of them? :)

**Comment by determinated** [comment]
I cant help much cuz i dont know how to fix things inside the source.
Maybe something in the skills template i'll be able to fix.

The major problem is locatad on motion xml.
This xml from 3.0 > is very different from this 2.7 and other lower versions.

From my knowledge is the major problem.
If wasn't for this a private server could be opened.

Anyway thank for this release, is the best 2.7 i've ever seen.

Congratz for your work.

I'll help with anything i can do.

**Comment by Jonathan57500** [comment]
Skill motions are used to determine correct annimation time.
Be carrefull that a few of them has change between 2.7 and 3.0 thats why times are different.
We already fix a few of them, but not all of them under all circumstances (buffs, spells, debuffs, etc.)

**Comment by determinated** [comment]
Yeah i think this is the major bug, after this thing fixed this files can have a awesome use.

**Comment by determinated** [comment]
Have a TODO with all the bugs?

**Comment by Jonathan57500** [comment]
Yes in the Wiki, but not complete (because nobody asked for added something ^^)
https://github.com/Jonathan57500/aion-lightning-2.7/wiki/TODO-List

**Comment by determinated** [comment]
Why this is on the TODO? Add Abyss transform restriction if there is no active siege
Retail you can use the Transformation if you have seeds.

Jonathan we can easily have a contact? Skype? Whatsapp?

After March 15 i'll be able to check this files all day and what i fix i'll send you. What i wont be able to fix i'll post here for you.

Everything that i'll fix will be retail like, ill NOT CUSTOM any files.

I really like this project and in a near future i would like to open a server.

Seems this files dont have many problems, awesome!

**Comment by determinated** [comment]
Do you have the client link?

**Comment by Jonathan57500** [comment]
I have no problem with retail fix, of course this is what we must do. My idea is to add additional custom content, and for each of them add a configuration option to enable or disable it. In your example, it could be something like in custom.properties: Allow Abyss transform if there is no active siege. Default value = true (retail like), but if he wants to make a custom server he can just disable this configuration.

Add custom things will allow some devs to add content, devs that don't want to work again and again on a retail server, they can add any content they want, with only one condition : this is optionnal and the administrator can choose to enable the custom or not (default set to not)

My Skype Nickname is "sipherion" (please confirm when you got it to edit this post)

I will make a list with some 2.7 clients, but I think you can Googlelize this to find a 2.7 EU client ;)

**Comment by determinated** [comment]
Done. i've add you on skype.
