### ISSUE TITLE
Admin's command for reboot or shutdown

### ISSUE THREAD

**Issue by YazooXepher** [Jonathan57500/aion-lightning-2.7#31]
Salut,
j'ai testé les commandes suivantes pour reboot ou shutdown : //sys restart //sys shutdown //restart 
rien à fonctionner auriez vous une aide à m'apporter s'il vous plait.

**Comment by Jonathan57500** [comment]
Salut,
//sys est un alias de la commande //system ; la bonne commande à utiliser est //system, ensuite tu peux ajouter tout alias que tu veux dans la base de données du Gameserver, table alias de mémoire (ou quelque chose dans le genre)

English version:
//sys is an alias of //system. To make //sys work you must add it as an alias in the Gameserver database
