### ISSUE TITLE
[ERROR] siege weapon does not work.

### ISSUE THREAD

**Issue by yonghwanil** [Jonathan57500/aion-lightning-2.7#61]
Hello,

I have a question this problem.

[Request]
- How to fix this problem ?

[Problem]
- Siege Weapon does not work (nothing any action).
* npc_id : 201054, 201055, 201056, 201057, 201058, 201059

[Contents]
- siege weapon summon is very well on siege area.
- but, siege weapon was not any action.
- only possible despawn.

thank you.

**Comment by Jonathan57500** [comment]
Siege weapons are not yet scripted on this emulator

**Comment by yonghwanil** [comment]
Can i simple change into the form of spirit master's summon spirit?

**Comment by Jonathan57500** [comment]
It could be interesting, you can try to do it if you think you can ;)

**Comment by yonghwanil** [comment]
Can you advice to me for that ? :)

my scripting skill is not good. ;

**Comment by Jonathan57500** [comment]
I tried one time, a long time ago, and was not successful, I should find time to try to fix it

**Comment by yonghwanil** [comment]
Thank you for your fast response.
I'm always thank you for you. ~
