### ISSUE TITLE
[ERROR] locale error on console

### ISSUE THREAD

**Issue by yonghwanil** [Jonathan57500/aion-lightning-2.7#62]
Hello

I have a question.

[Request]
1. How to chance default locale 'EN' ?
2. How to can i fix this problem ?

[Problem]
- display the error message when user login.
- error : 
09:21:58.784 ERROR[pool-4-thread-30]: - There were a locale website error for account 576. Set default locale as fr
09:21:58.784 INFO [pool-4-thread-30]: - Account authed: 576 = larcjw1

thank you.

**Comment by Jonathan57500** [comment]
This is an old custom that need the sql database of gameserver to be updated. Please refer to player command Locale to understand how does it work.
The default locale is set at player connexion, please refer to file data/scripts/system/database/mysql5/MySQL5PlayerDAO.java on line 314 (but it could be a good idea to move this into a custom config file right?)

**Comment by yonghwanil** [comment]
Thank you for your response !!

Thank you !
