### ISSUE TITLE
Is there any way to make a npc spawn when reach some set time 

### ISSUE THREAD

**Issue by FliesQQ** [Jonathan57500/aion-lightning-2.7#65]
Is there any way to make a npc spawn when reach some set time ?
such as when time reaches to 14:00 ,spawn some npcs at random position .

**Comment by FliesQQ** [comment]
such as spawn tears of luck . lights of luck

**Comment by Jonathan57500** [comment]
Hi,
Yes it is possible, please refer to #36 and next pull request to have examples
