### ISSUE TITLE
[Issue] fortress gate passed

### ISSUE THREAD

**Issue by yonghwanil** [Jonathan57500/aion-lightning-2.7#66]
Hello,

[Request]
- How to can i fix this problem ?

[Issue]
- Behind the door can attack targets across the door.

Thank you.

**Comment by Jonathan57500** [comment]
Enable geodata for partial fix of this issue. Some skills will still pass through the door but most will be blocked by client.

**Comment by yonghwanil** [comment]
Hello,
Can you tell me configuration detail ?
I'm all geodata configuration set 'true' in "geodata.properties".
but, still Behind the door can attack targets across the door.
