### ISSUE TITLE
[Issue] Monster & NPC walking on air.

### ISSUE THREAD

**Issue by yonghwanil** [Jonathan57500/aion-lightning-2.7#67]
Hello,

[Request]
- How to can i fix this problem ?

[Issue]
- Monster & NPC walking on air.
- ground monster & npc can walking on air.

Thank you.

**Comment by Jonathan57500** [comment]
Enable geodata to fix this issue in most "normal" use (no free fly, etc.)

**Comment by yonghwanil** [comment]
Thank you very much !!!!!!!!
