### ISSUE TITLE
How to open dredgion2

### ISSUE THREAD

**Issue by adslocao** [Jonathan57500/aion-lightning-2.7#7]
gameserver.dredgion2.enable = true
gameserver.dredgion.timer = 120
gameserver.dredgion.time = 0 0 18,22 ? * *
Open but no effect

**Comment by Jonathan57500** [comment]
Normaly Dredgion should work, but I know there is a lot of bugs if you try to join a group for Dredgion or anything else.
Did you get any error message in logs at 18h or 22h?

**Comment by adslocao** [comment]
0 0 5,6 ? * *
I changed it to 6 o'clock now, but I still can't do it.

**Comment by adslocao** [comment]
gameserver.dredgion.time = 0 0 6,22 ? * *
Is it because I have written the wrong parameter

**Comment by adslocao** [comment]
I will not play the replica of the lower right corner at 6.
